var WalletLogs = function() {
	return { 
	}

}();


WalletLogs.GH_CREATE_WITHDRAWAL_LOG_TYPE_ID = 31;

WalletLogs.DAILY_BONUS_GAME_DEPOSIT_LOG_TYPE_ID = 40;
WalletLogs.DAILY_GROWTH_DEPOSIT_LOG_TYPE_ID = 41;



WalletLogs.NEW_MEMBER_BONUS_FOR_FIRST_PH_LOG_TYPE_ID = 50;
WalletLogs.NEW_SPONSOR_BONUS_FOR_FIRST_10K_LOG_TYPE_ID = 51;








WalletLogs.LEVEL_INCOME_DEPOSIT_LOG_TYPE_ID = 60;
WalletLogs.DAILY_TASK_EARNING_FOR_PH_COMPLETED = 80;

WalletLogs.ADMIN_ADJUSTMENT_LOG_TYPE_ID = 100;

WalletLogs.LOH_BONUS_LOG_TYPE_ID = 105;

WalletLogs.SYSTEM_ERROR_CORRECTION_LOG_TYPE_ID = 200;
